include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    directives_ordering: ignore
    prefer_const_constructors: ignore
    deprecated_member_use: ignore
    unnecessary_cast: ignore

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - always_declare_return_types
    - unawaited_futures
    - directives_ordering
    - depend_on_referenced_packages
